openapi: 3.0.0
info:
  title: Flask Connexion Tester
  version: 1.0.0

paths:
  /hello:
    get:
      operationId: main.hello
      summary: Return a greeting
      parameters:
        - name: response_type
          in: query
          description: Type of response (normal, rate_limit)
          required: false
          schema:
            type: string
            enum: [normal, rate_limit]
      responses:
        '200':
          description: A successful response
          content:
            text/plain:
              schema:
                type: string
        '425':
          description: Rate Limit Reached
          content:
            text/plain:
              schema:
                type: string
